
%run '../ifile.py'
%run '../idata.py'
%run '../idataset.py'
%run '../imodel.py'
%run '../ker_model.py'
%run '../ker_model_loader.py'
%run '../tfl_model.py'
%run '../ai.py'
%run '../itrainer.py'
%run '../custom_functions.py'
%run '../custom_callbacks.py'
